/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesignn1;

import javafx.scene.Scene;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author W29CGRY
 */
public class Livingroom extends javax.swing.JFrame {
  //  Home home = new Home();
//Signin sign = new Signin();
             boolean clicked = true;


    /**
     * Creates new form Livingroom
     */
    public Livingroom() {
        initComponents();
    setResizable(false);
    
    }
//    Signin sign = new Signin();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MBack = new javax.swing.JMenuItem();
        MHead = new javax.swing.JMenuItem();
        Mtrannslate = new javax.swing.JMenuItem();
        Msource = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        bg2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        label4 = new java.awt.Label();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        jLabel20 = new javax.swing.JLabel();
        label6 = new java.awt.Label();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jPopupMenu1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPopupMenu1.setAlignmentX(1.0F);
        jPopupMenu1.setAlignmentY(1.0F);

        MBack.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        MBack.setText("Back ");
        MBack.setAlignmentX(1.0F);
        MBack.setAlignmentY(1.0F);
        MBack.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPopupMenu1.add(MBack);

        MHead.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        MHead.setText("ahead");
        MHead.setAlignmentX(1.0F);
        MHead.setAlignmentY(1.0F);
        MHead.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPopupMenu1.add(MHead);
        MHead.getAccessibleContext().setAccessibleDescription("");

        Mtrannslate.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Mtrannslate.setText("translation to Arabic ");
        Mtrannslate.setActionCommand("");
        Mtrannslate.setAlignmentY(1.0F);
        Mtrannslate.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPopupMenu1.add(Mtrannslate);

        Msource.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Msource.setText("View page source");
        Msource.setToolTipText("");
        Msource.setAlignmentY(1.0F);
        Msource.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPopupMenu1.add(Msource);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem8.setText("Open the image in a new tab ");
        jPopupMenu2.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem9.setText("Save image as ... ");
        jPopupMenu2.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem10.setText("Copy the image ");
        jPopupMenu2.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem11.setText("Copy the title of the image ");
        jPopupMenu2.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem12.setText("Search on Google for the image ");
        jPopupMenu2.add(jMenuItem12);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Living room");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1513, 4300));

        bg2.setBackground(new java.awt.Color(255, 255, 255));
        bg2.setToolTipText("");
        bg2.setComponentPopupMenu(jPopupMenu1);
        bg2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bg2.setFont(new java.awt.Font("Ink Free", 0, 36)); // NOI18N
        bg2.setMinimumSize(new java.awt.Dimension(1510, 3999));
        bg2.setPreferredSize(new java.awt.Dimension(1513, 4299));
        bg2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(244, 237, 220));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setText("customers service");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jLabel22.setText("Track requests");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jLabel23.setText("Warranty policy");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel24.setText("Return and exchange policy");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel25.setText("Discover");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));

        jLabel26.setText("Catalogs");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, -1, -1));

        jLabel27.setText("Exhibition sites");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jLabel28.setText("Store offers");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));

        jLabel29.setText("recently arrived");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel30.setText("about us ");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, -1, -1));

        jLabel31.setText("Opinions and comments");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, -1, -1));

        jLabel32.setText("About company");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, -1, -1));

        jLabel33.setText("News and events");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-whatsapp-100.png"))); // NOI18N
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 125, 90));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-technical-support-100.png"))); // NOI18N
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 125, 90));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-twitter-100.png"))); // NOI18N
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 125, 90));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-facebook-100.png"))); // NOI18N
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 210, 125, 90));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-instagram-old-100.png"))); // NOI18N
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 125, 90));

        jLabel39.setText("All rights reserved to Perfect Home © 2020");
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 552, 41));

        bg2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3900, 1510, 360));

        label2.setBackground(new java.awt.Color(205, 159, 20));
        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label2.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Your living room with us is beautiful ");
        bg2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 600, 80));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setText("70 SR ");
        bg2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 3510, 120, 50));

        jLabel2.setBackground(new java.awt.Color(220, 190, 139));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/White-2mmedia-AdobeStock.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setComponentPopupMenu(jPopupMenu2);
        bg2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1510, 650));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 29)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 105));
        jLabel4.setText("                 Floor lamp, white oval shape ");
        bg2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 3350, 700, 50));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("           Artificial patat in a bowl that does not need care. Ideal when you have better");
        bg2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 2810, 700, 50));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("                                               back cushions for added support.");
        bg2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2270, 700, 30));

        jButton1.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("loading more...");
        jButton1.setActionCommand("");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 3800, 430, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/chair3 (2).png"))); // NOI18N
        jLabel7.setComponentPopupMenu(jPopupMenu2);
        bg2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 910, 460, 440));

        label3.setBackground(new java.awt.Color(101, 64, 29));
        label3.setText(" ");
        bg2.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 870, 240, 520));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 29)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("                      Armchair, Vissle dark yellow ");
        bg2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1000, 700, 50));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("        Soft, round armrests and a back cushion provide a comfortable sitting ");
        bg2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1040, 700, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/fejka-artificial-potted-plant__0901035_PE641326_S5.png"))); // NOI18N
        jLabel19.setComponentPopupMenu(jPopupMenu2);
        bg2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 2690, 460, 450));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("                           feel warm thanks to the solid curved back panel.");
        bg2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1070, 700, 50));

        label1.setBackground(new java.awt.Color(204, 204, 204));
        label1.setText(" ");
        bg2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2650, 240, 520));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel11.setText("450 SR ");
        bg2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1110, 150, 50));

        jButton2.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Add to Cart");
        jButton2.setActionCommand("");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        bg2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 1170, 150, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/strandmon-wing-chair-skiftebo-light-beige__0513996_PE639275_S5.png"))); // NOI18N
        jLabel12.setComponentPopupMenu(jPopupMenu2);
        bg2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1530, 460, 440));

        label4.setBackground(java.awt.SystemColor.controlDkShadow);
        label4.setText(" ");
        bg2.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1490, 240, 520));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 29)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("                      Wing chair, Skiftebo light beige");
        bg2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 1580, 700, 50));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("       You can really relax in comfort because the high back on this chair provides extra  ");
        bg2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1640, 700, 50));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("         provides extra support. The cover is made of SKIFTEBO fabric from durable polyester.  ");
        bg2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 1690, 780, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel16.setText("530 SR ");
        bg2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 1740, 150, 50));

        jButton3.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Add to Cart");
        jButton3.setActionCommand("");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        bg2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 1820, 150, 40));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setText("                            things to do instead of watering and removing dead leaves.");
        bg2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 2860, 700, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/living_room_sofa-512 (1).png"))); // NOI18N
        jLabel18.setComponentPopupMenu(jPopupMenu2);
        bg2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 2110, 510, 440));

        label5.setBackground(new java.awt.Color(0, 37, 37));
        label5.setText(" ");
        bg2.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 2070, 240, 520));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/solleftea-floor-lamp__0880168_PE611358_S5.png"))); // NOI18N
        jLabel20.setComponentPopupMenu(jPopupMenu2);
        bg2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 3280, 500, 430));

        label6.setBackground(new java.awt.Color(10, 13, 64));
        label6.setText(" ");
        bg2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 3230, 240, 520));

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Tahoma", 2, 29)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(2, 53, 53));
        jLabel40.setText("                         3-seat sofa, Finnsta");
        bg2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2180, 700, 50));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel41.setText("                                      that gives wonderful and diffused lighting.");
        bg2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 3440, 700, 50));

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel42.setText("           The cover is easy to keep clean since it is removable and machine wash.");
        bg2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 2300, 700, 30));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel43.setText("999 SR");
        bg2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 2340, 130, 50));

        jButton4.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Add to Cart");
        jButton4.setActionCommand("");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        bg2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 2400, 150, 40));

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Tahoma", 2, 29)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(153, 153, 153));
        jLabel44.setText("                 Artificial plant in pots, in / outdoor");
        bg2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 2760, 700, 50));

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel45.setText("   SÖDERHAMN session series allow you a deep, low and soft session with additional");
        bg2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2230, 700, 50));

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel46.setText("You can create a smooth and comfortable atmosphere in your home with a paper lamp ");
        bg2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 3400, 700, 50));

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel47.setText("29 SR ");
        bg2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 2910, 120, 50));

        jButton5.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Add to Cart");
        jButton5.setActionCommand("");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        bg2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2970, 150, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, -1));

        jButton6.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Add to Cart");
        jButton6.setActionCommand("");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        bg2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 3580, 150, 40));
        bg2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 3190, 1210, 40));
        bg2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1420, 1210, 60));
        bg2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2030, 1210, 40));
        bg2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 2610, 1210, 40));

        jPanel2.setBackground(new java.awt.Color(244, 237, 220));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-home-page-100.png"))); // NOI18N
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 137, 84));

        jLabel48.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(204, 0, 51));
        jLabel48.setText("Perfect Home ");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 130, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SR", "EUR", "USD", "JPY", "AUD", "AED", "BHD" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 130, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 50, 220, 30));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-search-30.png"))); // NOI18N
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 40, -1, 50));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-add-shopping-cart-50.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 50, 40));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-person-48.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 40, 40));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-heart-50.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 50, 40));

        bg2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 120));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-heart-26.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        bg2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1170, 30, 30));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-heart-26.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        bg2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 2400, 30, 30));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-heart-26.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        bg2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 2970, 30, 30));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-heart-26.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        bg2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 3580, 30, 30));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-heart-26.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        bg2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 1820, 30, 30));

        jScrollPane1.setViewportView(bg2);

        jMenu1.setText("Home");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-home-32.png"))); // NOI18N
        jMenuItem1.setText("Home...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Room");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-bedroom-32.png"))); // NOI18N
        jMenuItem2.setText("Bedroom...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-sofa-32.png"))); // NOI18N
        jMenuItem3.setText("Living room...");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-bathtub-32.png"))); // NOI18N
        jMenuItem4.setText("Bathroom...");
        jMenuItem4.setToolTipText("");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-kitchen-room-32.png"))); // NOI18N
        jMenuItem5.setText("Kichen...");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-baby-mobile-30.png"))); // NOI18N
        jMenuItem6.setText("Babyroom...");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sign-in");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-lock-32.png"))); // NOI18N
        jMenuItem7.setText("signin...");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 4253, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     //home.setVisible(true);
     //setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
      // sign.setVisible(true);
       //this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(this, "Please wait while the page loads :) .... ");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
JOptionPane.showMessageDialog(this, "Added to cart");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
JOptionPane.showMessageDialog(this, "Added to cart");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
JOptionPane.showMessageDialog(this, "Added to cart");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
JOptionPane.showMessageDialog(this, "Added to cart");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
JOptionPane.showMessageDialog(this, "Added to cart");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
JOptionPane.showMessageDialog(this, "Added to Wish list ");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        //sign.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Added to Wish list ");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Added to Wish list ");

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Added to Wish list ");

    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
JOptionPane.showMessageDialog(this, "Added to Wish list ");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        JOptionPane.showMessageDialog(this, "Searching .... ");

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livingroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livingroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livingroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livingroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Livingroom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MBack;
    private javax.swing.JMenuItem MHead;
    private javax.swing.JMenuItem Msource;
    private javax.swing.JMenuItem Mtrannslate;
    private javax.swing.JPanel bg2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    // End of variables declaration//GEN-END:variables

}
