/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesignn1;

import javax.swing.JFrame;
import javax.swing.JFrame;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author W29CGRY
 */
public class Register extends javax.swing.JFrame {
    /**
     * Creates new form Page1
     */
    public Register() {
        initComponents();
        setResizable(false);
    }
   // Livingroom living = new Livingroom();
    Home home = new Home();
    Livingroom living= new Livingroom();
  //  Signin sign = new Signin();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        MBack = new javax.swing.JMenuItem();
        MHead = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        Mtrannslate = new javax.swing.JMenuItem();
        Msource = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        cpw = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        pw = new javax.swing.JPasswordField();
        lbl_ln = new javax.swing.JLabel();
        lbl_em = new javax.swing.JLabel();
        lbl_pw = new javax.swing.JLabel();
        lbl_fn = new javax.swing.JLabel();
        lbl_cpw = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jPopupMenu1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPopupMenu1.setAlignmentX(1.0F);
        jPopupMenu1.setAlignmentY(1.0F);

        MBack.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        MBack.setText("Back ");
        MBack.setAlignmentX(1.0F);
        MBack.setAlignmentY(1.0F);
        MBack.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPopupMenu1.add(MBack);

        MHead.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        MHead.setText("ahead");
        MHead.setAlignmentX(1.0F);
        MHead.setAlignmentY(1.0F);
        MHead.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPopupMenu1.add(MHead);

        jMenuItem8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jMenuItem8.setText("Reload...");
        jPopupMenu1.add(jMenuItem8);

        Mtrannslate.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Mtrannslate.setText("translation to Arabic ");
        Mtrannslate.setActionCommand("");
        Mtrannslate.setAlignmentY(1.0F);
        Mtrannslate.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPopupMenu1.add(Mtrannslate);

        Msource.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Msource.setText("View page source");
        Msource.setToolTipText("");
        Msource.setAlignmentY(1.0F);
        Msource.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPopupMenu1.add(Msource);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem9.setText("Open the image in a new tab ");
        jPopupMenu2.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem10.setText("Save image as ... ");
        jPopupMenu2.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem11.setText("Copy the image ");
        jPopupMenu2.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem12.setText("Copy the title of the image ");
        jPopupMenu2.add(jMenuItem12);

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem13.setText("Search on Google for the image ");
        jPopupMenu2.add(jMenuItem13);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setName("Signin"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1513, 1352));
        setResizable(false);
        addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                formHierarchyChanged(evt);
            }
        });
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1513, 1352));
        jScrollPane1.setRequestFocusEnabled(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setComponentPopupMenu(jPopupMenu1);
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bg.setPreferredSize(new java.awt.Dimension(1513, 1450));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Sign Up");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 238, 68));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("Email :      ");
        bg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 130, 70));

        em.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        em.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emKeyReleased(evt);
            }
        });
        bg.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 340, 60));

        cpw.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpwActionPerformed(evt);
            }
        });
        cpw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpwKeyReleased(evt);
            }
        });
        bg.add(cpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 710, 340, 60));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setText("confirm password: ");
        bg.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 700, 270, 80));

        jButton1.setBackground(new java.awt.Color(240, 212, 170));
        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setText("Sign up");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 830, 310, 70));
        jButton1.getAccessibleContext().setAccessibleDescription("");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-login-100.png"))); // NOI18N
        jLabel18.setComponentPopupMenu(jPopupMenu2);
        bg.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 130, 100));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bg.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 830, -1, -1));

        jPanel8.setBackground(new java.awt.Color(244, 237, 220));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setText("customers service");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jLabel22.setText("Track requests");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jLabel23.setText("Warranty policy");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel24.setText("Return and exchange policy");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel25.setText("Discover");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));

        jLabel26.setText("Catalogs");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, -1, -1));

        jLabel27.setText("Exhibition sites");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jLabel28.setText("Store offers");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));

        jLabel29.setText("recently arrived");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel30.setText("about us ");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, -1, -1));

        jLabel31.setText("Opinions and comments");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, -1, -1));

        jLabel32.setText("About company");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, -1, -1));

        jLabel33.setText("News and events");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-whatsapp-100.png"))); // NOI18N
        jLabel34.setComponentPopupMenu(jPopupMenu2);
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 125, 90));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-technical-support-100.png"))); // NOI18N
        jLabel35.setComponentPopupMenu(jPopupMenu2);
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 125, 90));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-twitter-100.png"))); // NOI18N
        jLabel36.setComponentPopupMenu(jPopupMenu2);
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 125, 90));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-facebook-100.png"))); // NOI18N
        jLabel37.setComponentPopupMenu(jPopupMenu2);
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 210, 125, 90));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-instagram-old-100.png"))); // NOI18N
        jLabel38.setComponentPopupMenu(jPopupMenu2);
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 125, 90));

        jLabel39.setText("All rights reserved to Perfect Home © 2020");
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 552, 41));

        bg.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1090, 1510, 370));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("First Name : ");
        bg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 150, 70));

        fn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnKeyReleased(evt);
            }
        });
        bg.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 340, 60));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("Last Name:");
        bg.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 140, 70));

        ln.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        ln.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnKeyReleased(evt);
            }
        });
        bg.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 340, 60));

        jLabel40.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel40.setText("Password: ");
        bg.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 160, 80));

        pw.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwActionPerformed(evt);
            }
        });
        pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwKeyReleased(evt);
            }
        });
        bg.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 340, 60));

        lbl_ln.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_ln.setForeground(new java.awt.Color(255, 51, 0));
        bg.add(lbl_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 220, 30));

        lbl_em.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_em.setForeground(new java.awt.Color(255, 51, 0));
        bg.add(lbl_em, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 220, 30));

        lbl_pw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_pw.setForeground(new java.awt.Color(255, 51, 0));
        bg.add(lbl_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, 220, 30));

        lbl_fn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_fn.setForeground(new java.awt.Color(255, 51, 0));
        bg.add(lbl_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 220, 30));

        lbl_cpw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_cpw.setForeground(new java.awt.Color(255, 0, 0));
        bg.add(lbl_cpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 770, 220, 30));

        jScrollPane1.setViewportView(bg);

        jMenuBar1.setBackground(new java.awt.Color(240, 222, 153));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu2.setText("Home ");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-home-32.png"))); // NOI18N
        jMenuItem6.setText("Home...");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Room");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-bedroom-32.png"))); // NOI18N
        jMenuItem1.setText("Bedroom...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-sofa-32.png"))); // NOI18N
        jMenuItem2.setText("Living room...");
        jMenuItem2.setToolTipText("");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-bathtub-32.png"))); // NOI18N
        jMenuItem3.setText("bathroom...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-kitchen-room-32.png"))); // NOI18N
        jMenuItem4.setText("Kichen...");
        jMenuItem4.setToolTipText("");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-baby-mobile-30.png"))); // NOI18N
        jMenuItem5.setText("Babyroom...");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sign-in");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guidesignn1/images/icons8-lock-32.png"))); // NOI18N
        jMenuItem7.setText("Sigh-in...");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1528, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1528, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Signin ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpwActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(fn.getText().trim().isEmpty() && ln.getText().trim().isEmpty() && em.getText().trim().isEmpty() && pw.getText().trim().isEmpty() && cpw.getText().trim().isEmpty()){
    lbl_fn.setText("First name is Empty ");
    lbl_ln.setText("Last name is Empty ");
    lbl_em.setText("Email is Empty ");
    lbl_pw.setText("Pawwword is Empty ");
    lbl_cpw.setText("confirm password is Empty ");

} 
else if (fn.getText().trim().isEmpty())
{
    lbl_fn.setText("First name is Empty ");
}
else if (ln.getText().trim().isEmpty())
{
      lbl_ln.setText("Last name is Empty ");
}
else if (ln.getText().trim().isEmpty())
{
      lbl_ln.setText("Last name is Empty ");
}
else if (em.getText().trim().isEmpty())
{
      lbl_em.setText("Email is Empty ");
}
else if (pw.getText().trim().isEmpty())
{
      lbl_pw.setText("Password is Empty ");
}
else if (cpw.getText().trim().isEmpty())
{
      lbl_cpw.setText("confirm password is Empty "); 
}
else
{
        JOptionPane.showMessageDialog(this, "Welcome to our website :) ");

      home.setVisible(true); // open home frame 
      this.setVisible(false); // close current frame
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseWheelMoved

    private void formHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formHierarchyChanged

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       living.setVisible(true);
       this.setVisible(false); // close current frame      
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       this.setVisible(false); // close current frame
       home.setVisible(true); // open home frame        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       //   sign.setVisible(true);
        //  this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwActionPerformed

    private void fnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyReleased
lbl_fn.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_fnKeyReleased

    private void lnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnKeyReleased
lbl_ln.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_lnKeyReleased

    private void emKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emKeyReleased
lbl_em.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_emKeyReleased

    private void pwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwKeyReleased
lbl_pw.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_pwKeyReleased

    private void cpwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpwKeyReleased
lbl_cpw.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_cpwKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MBack;
    private javax.swing.JMenuItem MHead;
    private javax.swing.JMenuItem Msource;
    private javax.swing.JMenuItem Mtrannslate;
    private javax.swing.JPanel bg;
    private javax.swing.JPasswordField cpw;
    private javax.swing.JTextField em;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cpw;
    private javax.swing.JLabel lbl_em;
    private javax.swing.JLabel lbl_fn;
    private javax.swing.JLabel lbl_ln;
    private javax.swing.JLabel lbl_pw;
    private javax.swing.JTextField ln;
    private javax.swing.JPasswordField pw;
    // End of variables declaration//GEN-END:variables
}

